// <auto-generated />
using System;
using Amplify_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amplify_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128082750_28_01_26")]
    partial class _28_01_26
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amplify_backend.Model.Albums", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("artistId")
                        .HasColumnType("uuid");

                    b.Property<string>("coverArtUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("genre")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("releaseDate")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("id");

                    b.HasIndex("artistId");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("Amplify_backend.Model.Artists", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("Amplify_backend.Model.LikedSongs", b =>
                {
                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("songId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("userId", "songId");

                    b.HasIndex("songId");

                    b.ToTable("liked_songs", (string)null);
                });

            modelBuilder.Entity("Amplify_backend.Model.PlaylistSongs", b =>
                {
                    b.Property<Guid>("playlistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("songId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("addedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("position")
                        .HasColumnType("integer");

                    b.HasKey("playlistId", "songId");

                    b.HasIndex("songId");

                    b.ToTable("playlist_songs", (string)null);
                });

            modelBuilder.Entity("Amplify_backend.Model.Playlists", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("coverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("playlists");
                });

            modelBuilder.Entity("Amplify_backend.Model.Songs", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("albumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("artistId")
                        .HasColumnType("uuid");

                    b.Property<int>("bitrate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("durationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("fileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("storageType")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("trackNumber")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("albumId");

                    b.HasIndex("artistId");

                    b.ToTable("songs");
                });

            modelBuilder.Entity("Amplify_backend.Model.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("avatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("displayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Amplify_backend.Model.Albums", b =>
                {
                    b.HasOne("Amplify_backend.Model.Artists", "artist")
                        .WithMany("albums")
                        .HasForeignKey("artistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("artist");
                });

            modelBuilder.Entity("Amplify_backend.Model.LikedSongs", b =>
                {
                    b.HasOne("Amplify_backend.Model.Songs", "song")
                        .WithMany()
                        .HasForeignKey("songId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amplify_backend.Model.Users", "user")
                        .WithMany("LikedSongs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("song");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Amplify_backend.Model.PlaylistSongs", b =>
                {
                    b.HasOne("Amplify_backend.Model.Playlists", "playlist")
                        .WithMany("songs")
                        .HasForeignKey("playlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amplify_backend.Model.Songs", "song")
                        .WithMany("playlists")
                        .HasForeignKey("songId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playlist");

                    b.Navigation("song");
                });

            modelBuilder.Entity("Amplify_backend.Model.Playlists", b =>
                {
                    b.HasOne("Amplify_backend.Model.Users", "user")
                        .WithMany("Playlists")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Amplify_backend.Model.Songs", b =>
                {
                    b.HasOne("Amplify_backend.Model.Albums", "album")
                        .WithMany("songs")
                        .HasForeignKey("albumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amplify_backend.Model.Artists", "artist")
                        .WithMany("songs")
                        .HasForeignKey("artistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("artist");
                });

            modelBuilder.Entity("Amplify_backend.Model.Albums", b =>
                {
                    b.Navigation("songs");
                });

            modelBuilder.Entity("Amplify_backend.Model.Artists", b =>
                {
                    b.Navigation("albums");

                    b.Navigation("songs");
                });

            modelBuilder.Entity("Amplify_backend.Model.Playlists", b =>
                {
                    b.Navigation("songs");
                });

            modelBuilder.Entity("Amplify_backend.Model.Songs", b =>
                {
                    b.Navigation("playlists");
                });

            modelBuilder.Entity("Amplify_backend.Model.Users", b =>
                {
                    b.Navigation("LikedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
